# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(800, 600)
        MainWindow.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(0, 0, 0, 255), stop:1 rgba(255, 255, 255, 255));")
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.userLoginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.userLoginBtn.setGeometry(QtCore.QRect(230, 190, 56, 17))
        self.userLoginBtn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(46, 182, 255), stop:1 rgba(255, 255, 255, 255));")
        self.userLoginBtn.setObjectName("userLoginBtn")
        self.adminLoginBtn = QtWidgets.QPushButton(self.centralwidget)
        self.adminLoginBtn.setGeometry(QtCore.QRect(230, 230, 56, 17))
        self.adminLoginBtn.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(46, 182, 255), stop:1 rgba(255, 255, 255, 255));")
        self.adminLoginBtn.setObjectName("adminLoginBtn")
        self.UsernameEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.UsernameEdit.setGeometry(QtCore.QRect(120, 90, 113, 20))
        self.UsernameEdit.setObjectName("UsernameEdit")
        self.PasswordEdit = QtWidgets.QLineEdit(self.centralwidget)
        self.PasswordEdit.setGeometry(QtCore.QRect(120, 150, 113, 20))
        self.PasswordEdit.setObjectName("PasswordEdit")
        self.label = QtWidgets.QLabel(self.centralwidget)
        self.label.setGeometry(QtCore.QRect(164, 20, 178, 20))
        self.label.setMinimumSize(QtCore.QSize(91, 0))
        self.label.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0), stop:1 rgba(255, 255, 255, 255));")
        self.label.setObjectName("label")
        self.label_2 = QtWidgets.QLabel(self.centralwidget)
        self.label_2.setGeometry(QtCore.QRect(70, 70, 56, 14))
        self.label_2.setStyleSheet("\n"
"background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0), stop:1 rgba(255, 255, 255, 255));")
        self.label_2.setObjectName("label_2")
        self.label_3 = QtWidgets.QLabel(self.centralwidget)
        self.label_3.setGeometry(QtCore.QRect(70, 130, 54, 14))
        self.label_3.setStyleSheet("background-color: qlineargradient(spread:pad, x1:0, y1:0, x2:1, y2:0, stop:0 rgba(255, 0, 0), stop:1 rgba(255, 255, 255, 255));")
        self.label_3.setObjectName("label_3")
        MainWindow.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(MainWindow)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 800, 18))
        self.menubar.setObjectName("menubar")
        self.menuCinema_Ticket_System = QtWidgets.QMenu(self.menubar)
        self.menuCinema_Ticket_System.setObjectName("menuCinema_Ticket_System")
        MainWindow.setMenuBar(self.menubar)
        self.statusbar = QtWidgets.QStatusBar(MainWindow)
        self.statusbar.setObjectName("statusbar")
        MainWindow.setStatusBar(self.statusbar)
        self.menubar.addAction(self.menuCinema_Ticket_System.menuAction())

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "MainWindow"))
        self.userLoginBtn.setText(_translate("MainWindow", "User login"))
        self.adminLoginBtn.setText(_translate("MainWindow", "Admin login"))
        self.label.setText(_translate("MainWindow", "<html><head/><body><p align=\"center\"><span style=\" font-size:16pt; font-weight:600;\">Cinema Ticket System</span></p></body></html>"))
        self.label_2.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Username</span></p></body></html>"))
        self.label_3.setText(_translate("MainWindow", "<html><head/><body><p><span style=\" font-size:11pt; font-weight:600;\">Password</span></p></body></html>"))
        self.menuCinema_Ticket_System.setTitle(_translate("MainWindow", "Cinema Ticket System"))
