from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(500, 550)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(60, 60, 60, 60)
        self.verticalLayout.setSpacing(20)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(28)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_subtitle = QtWidgets.QLabel(self.centralwidget)
        self.lbl_subtitle.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_subtitle.setFont(font)
        self.lbl_subtitle.setObjectName("lbl_subtitle")
        self.verticalLayout.addWidget(self.lbl_subtitle)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.btn_user = QtWidgets.QPushButton(self.centralwidget)
        self.btn_user.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_user.setFont(font)
        self.btn_user.setObjectName("btn_user")
        self.verticalLayout.addWidget(self.btn_user)
        self.btn_admin = QtWidgets.QPushButton(self.centralwidget)
        self.btn_admin.setMinimumSize(QtCore.QSize(0, 45))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_admin.setFont(font)
        self.btn_admin.setObjectName("btn_admin")
        self.verticalLayout.addWidget(self.btn_admin)
        spacerItem = QtWidgets.QSpacerItem(20, 20, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_exit = QtWidgets.QPushButton(self.centralwidget)
        self.btn_exit.setMinimumSize(QtCore.QSize(0, 40))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_exit.setFont(font)
        self.btn_exit.setObjectName("btn_exit")
        self.verticalLayout.addWidget(self.btn_exit)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "ECHOPLEX - Cinema Booking"))
        self.lbl_title.setText(_translate("MainWindow", "ECHOPLEX"))
        self.lbl_subtitle.setText(_translate("MainWindow", "CINEMA TICKET BOOKING SYSTEM"))
        self.btn_user.setText(_translate("MainWindow", "User Login"))
        self.btn_admin.setText(_translate("MainWindow", "Admin Login"))
        self.btn_exit.setText(_translate("MainWindow", "Exit"))
