# -*- coding: utf-8 -*-

# Form implementation generated from reading ui file 'user_login.ui'
#
# Created by: PyQt5 UI code generator 5.15.11
#
# WARNING: Any manual changes made to this file will be lost when pyuic5 is
# run again.  Do not edit this file unless you know what you are doing.


from PyQt5 import QtCore, QtGui, QtWidgets


class Ui_MainWindow(object):
    def setupUi(self, MainWindow):
        MainWindow.setObjectName("MainWindow")
        MainWindow.resize(450, 400)
        self.centralwidget = QtWidgets.QWidget(MainWindow)
        self.centralwidget.setObjectName("centralwidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.centralwidget)
        self.verticalLayout.setContentsMargins(60, 50, 60, 50)
        self.verticalLayout.setSpacing(16)
        self.verticalLayout.setObjectName("verticalLayout")
        self.lbl_title = QtWidgets.QLabel(self.centralwidget)
        self.lbl_title.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(22)
        font.setBold(True)
        font.setWeight(75)
        self.lbl_title.setFont(font)
        self.lbl_title.setObjectName("lbl_title")
        self.verticalLayout.addWidget(self.lbl_title)
        self.lbl_heading = QtWidgets.QLabel(self.centralwidget)
        self.lbl_heading.setAlignment(QtCore.Qt.AlignCenter)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_heading.setFont(font)
        self.lbl_heading.setObjectName("lbl_heading")
        self.verticalLayout.addWidget(self.lbl_heading)
        self.line = QtWidgets.QFrame(self.centralwidget)
        self.line.setFrameShape(QtWidgets.QFrame.HLine)
        self.line.setFrameShadow(QtWidgets.QFrame.Sunken)
        self.line.setObjectName("line")
        self.verticalLayout.addWidget(self.line)
        self.lbl_username = QtWidgets.QLabel(self.centralwidget)
        font = QtGui.QFont()
        font.setPointSize(11)
        self.lbl_username.setFont(font)
        self.lbl_username.setObjectName("lbl_username")
        self.verticalLayout.addWidget(self.lbl_username)
        self.input_username = QtWidgets.QLineEdit(self.centralwidget)
        self.input_username.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.input_username.setFont(font)
        self.input_username.setObjectName("input_username")
        self.verticalLayout.addWidget(self.input_username)
        spacerItem = QtWidgets.QSpacerItem(20, 10, QtWidgets.QSizePolicy.Minimum, QtWidgets.QSizePolicy.Expanding)
        self.verticalLayout.addItem(spacerItem)
        self.btn_continue = QtWidgets.QPushButton(self.centralwidget)
        self.btn_continue.setMinimumSize(QtCore.QSize(0, 42))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.btn_continue.setFont(font)
        self.btn_continue.setObjectName("btn_continue")
        self.verticalLayout.addWidget(self.btn_continue)
        self.btn_back = QtWidgets.QPushButton(self.centralwidget)
        self.btn_back.setMinimumSize(QtCore.QSize(0, 38))
        font = QtGui.QFont()
        font.setPointSize(11)
        self.btn_back.setFont(font)
        self.btn_back.setObjectName("btn_back")
        self.verticalLayout.addWidget(self.btn_back)
        MainWindow.setCentralWidget(self.centralwidget)

        self.retranslateUi(MainWindow)
        QtCore.QMetaObject.connectSlotsByName(MainWindow)

    def retranslateUi(self, MainWindow):
        _translate = QtCore.QCoreApplication.translate
        MainWindow.setWindowTitle(_translate("MainWindow", "User Login - ECHOPLEX"))
        self.lbl_title.setText(_translate("MainWindow", "ECHOPLEX"))
        self.lbl_heading.setText(_translate("MainWindow", "USER LOGIN"))
        self.lbl_username.setText(_translate("MainWindow", "Username"))
        self.input_username.setPlaceholderText(_translate("MainWindow", "Enter your username"))
        self.btn_continue.setText(_translate("MainWindow", "Continue"))
        self.btn_back.setText(_translate("MainWindow", "Back"))
